### ISSUE TITLE
pip install bottleneck requirement missing

### ISSUE THREAD

**Issue by TeoSakel** [cellnopt/cellnopt#109]
Upon fresh installation with pip, import fails with:
`ImportError: No module named bottleneck`

And `pip show cno` does not list bottleneck as a requirement:

Metadata-Version: 2.0
Name: cno
Version: 0.1.3
Summary: CNO (Cell Net Optimiser): Manipulate, Visualise and Optimise Biological Networks to Perturbation Data.
Home-page: ['http://pypi.python.org/pypi/cno']
Author: Thomas Cokelaer
Author-email: cokelaer@ebi.ac.uk
License: BSD
Location: /usr/local/lib/python2.7/dist-packages
**Requires: networkx, scipy, pulp, numexpr, numpy, pandas, matplotlib, bioservices, easydev, biokit, colormap, wrapt**
Entry-points:
  [console_scripts]
  cno_boolean = cno.boolean.cnorbool:standalone
  cno_dt = cno.boolean.cnordt:standalone
  cno_fuzzy = cno.fuzzy.cnorfuzzy:standalone
  cno_milp = cno.milp.model:standalone
  cno_ode = cno.ode.cnorode:standalone
  cno_plotmodel = cno.apps.plotmodel:plotmodel

**Comment by cokelaer** [comment]
I've uploaded a new version on pypi (0.1.4) where I fixed the missing dependencies. 
Note that newest version of networkx requires a couple of changes but should not have nay impact on the API.
